### ISSUE TITLE
FEATURE: sync to local filesystem

### ISSUE THREAD

**Issue by kronn** [puzzle/ccli#22]
I would like to sync from a source (cryptopus, openshift, kubernetes) to the local file system to edit the secrets there. These secrets do not need to be in plain-text. They could be encrypted and editable only by another command like `cry edit ...`. 

My main  pain point is that I want fewer moving parts. Also, I want to have a little more control from where and to where I transfer the secrets.

**Comment by severinraez** [comment]
Good news: We might now be able to achieve all of this by using both cry and CIA together (see our ops channel). I suggest we further discuss this over in the ops channel and open a new issue if applicable.
